version: '3.8'

services:
  postgres:
    image: postgres:alpine3.20
    container_name: quasar_nest_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edgar-sync
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
