export const PG_CONNECTION = "PG_CONNECTION";
export const PG_SYNC_CONNECTION = "PG_SYNC_CONNECTION";
export const MONGO_CONNECTION = "MONGO_CONNECTION";
export const MINIO_CONNECTION = "MINIO_CONNECTION";